title: EngageSquared Security Deliveries
description: Security consulting methodology
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-minima
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - "*.md"
